import { BedDouble, Coffee, Moon, Sun } from "lucide-react";
import { useState } from "react";
import Button from "../../ui/Button";
import Input from "../../ui/Input";

const periods = [{ value: "morning", icon: Sun }, { value: "afternoon", icon: Coffee }, { value: "evening", icon: Moon }, { value: "night", icon: BedDouble }];
function RoutineStep({ nextStep, prevStep, data, updateData }) {
  const [routine, setRoutine] = useState({ wake_up_time: data.wake_up_time || "", sleep_time: data.sleep_time || "", preferred_study_time: data.preferred_study_time || "", daily_study_target: data.daily_study_target || "", break_duration: data.break_duration || "25" });
  const update = (event) => setRoutine((current) => ({ ...current, [event.target.name]: event.target.value }));
  const complete = routine.wake_up_time && routine.sleep_time && routine.preferred_study_time && routine.daily_study_target && routine.break_duration;
  return <section><header className="mb-7"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-sky-50 text-sky-600"><Sun size={20} /></div><h1 className="text-2xl font-semibold text-gray-900">Set your study rhythm</h1><p className="mt-2 text-gray-500">We will use these preferences to suggest focus blocks at useful times.</p></header><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-gray-700">Wake-up time<Input className="mt-2" type="time" name="wake_up_time" value={routine.wake_up_time} onChange={update} /></label><label className="text-sm font-medium text-gray-700">Sleep time<Input className="mt-2" type="time" name="sleep_time" value={routine.sleep_time} onChange={update} /></label></div><p className="mt-6 text-sm font-medium text-gray-700">Preferred study period</p><div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-4">{periods.map(({ value, icon: Icon }) => <button type="button" key={value} onClick={() => setRoutine((current) => ({ ...current, preferred_study_time: value }))} className={`flex min-h-20 flex-col items-center justify-center gap-2 rounded-lg border text-sm font-medium capitalize transition ${routine.preferred_study_time === value ? "border-indigo-500 bg-indigo-50 text-indigo-700" : "border-gray-200 text-gray-600 hover:border-indigo-200"}`}><Icon size={18} />{value}</button>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-gray-700">Daily study target (hours)<Input className="mt-2" min="1" max="12" type="number" name="daily_study_target" value={routine.daily_study_target} onChange={update} /></label><label className="text-sm font-medium text-gray-700">Preferred break duration (minutes)<Input className="mt-2" min="5" max="120" type="number" name="break_duration" value={routine.break_duration} onChange={update} /></label></div><footer className="mt-9 flex justify-between"><Button variant="secondary" onClick={prevStep}>Back</Button><Button onClick={() => { updateData(routine); nextStep(); }} disabled={!complete}>Continue</Button></footer></section>;
}
export default RoutineStep;
