# Generated by Django 6.0.8 on 2026-08-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('wake_up_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
                ('preferred_study_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('goal', models.CharField(choices=[('placements', 'Placements'), ('semester_exam', 'Semester Exam'), ('gate', 'GATE'), ('higher_studies', 'Higher Studies'), ('other', 'Other')], max_length=30)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
