# Generated by Django 6.0.8 on 2026-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_study_target',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
