# Generated by Django 6.0.8 on 2026-08-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_schedule_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_study_times',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
